name: kulturaquest
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.2.12  # For splash screen

flutter:
  uses-material-design: true
  assets:
    - assets/images/photo1.png
    - assets/images/k_logo.png
    - assets/images/food.jpg
    - assets/videos/video1.mp4

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/k_logo.png
  android: true
  ios: true
