name: kulturaquest
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  js: ^0.7.1 # dun to sa mahabang lintik na error pag nirurunhaha ito lang pala

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.2.12  # For splash screen

flutter:
  uses-material-design: true
  assets:
    - assets/images/photo1.png
    - assets/images/k_logo.png
    - assets/images/food.jpg
    - assets/videos/video1.mp4

flutter_native_splash:  ## U cant see this on dart code, since this is here lang
  color: "#ffffff"
  image: assets/images/k_logo.png
  android: true
  ios: true



