// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHGxVHdyqDqspehGl4mgLuRY_E_PerKPA',
    appId: '1:98369579120:web:6c2a8c61191f97756e2cb5',
    messagingSenderId: '98369579120',
    projectId: 'kulturaquestfire',
    authDomain: 'kulturaquestfire.firebaseapp.com',
    storageBucket: 'kulturaquestfire.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYEINH1NZYA3ovY1ypU1ekU-V0gFy4ESc',
    appId: '1:98369579120:android:316fb2cbc0b1da516e2cb5',
    messagingSenderId: '98369579120',
    projectId: 'kulturaquestfire',
    storageBucket: 'kulturaquestfire.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0bw8Bg9606YHVmd6Li2eyBhmvGlpVMaY',
    appId: '1:98369579120:ios:8e81d1ef170322f86e2cb5',
    messagingSenderId: '98369579120',
    projectId: 'kulturaquestfire',
    storageBucket: 'kulturaquestfire.firebasestorage.app',
    iosBundleId: 'com.example.kulturaquest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0bw8Bg9606YHVmd6Li2eyBhmvGlpVMaY',
    appId: '1:98369579120:ios:8e81d1ef170322f86e2cb5',
    messagingSenderId: '98369579120',
    projectId: 'kulturaquestfire',
    storageBucket: 'kulturaquestfire.firebasestorage.app',
    iosBundleId: 'com.example.kulturaquest',
  );
}
